name: Swift

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: [ self-hosted, ios ]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "build here" # swift build -v
    - name: Run tests
      run: echo "test here" # swift test -v
