name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  tags:
    - '*'
    
jobs:
  build:

    runs-on: [ self-hosted, ios ]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "build here" # swift build -v
    - name: Run tests
      run: echo "test here" # swift test -v
